### ISSUE TITLE
Unsupported Method

### ISSUE THREAD

**Issue by jontowles** [grails-plugins/grails-spring-security-ldap#11]
We are seeing this issue when trying to run this:

| Error Error initializing classpath: Unsupported method: GrailsClasspath.getProfileDependencies().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model. (NOTE: Stack trace has been filtered. Use --verbose to see entire trace.)
org.gradle.tooling.model.UnsupportedMethodException: Unsupported method: GrailsClasspath.getProfileDependencies().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.
at org.gradle.tooling.model.internal.Exceptions.unsupportedMethod(Exceptions.java:34)
at org.gradle.tooling.internal.adapter.ProtocolToModelAdapter$InvocationHandlerImpl.invoke(ProtocolToModelAdapter.java:240)
at com.sun.proxy.$Proxy10.getProfileDependencies(Unknown Source)
at org.grails.cli.GrailsCli$1.readFromGradle(GrailsCli.groovy:539)
at org.grails.cli.GrailsCli$1.readFromGradle(GrailsCli.groovy)
at org.grails.cli.gradle.cache.CachedGradleOperation$_call_closure1.doCall(CachedGradleOperation.groovy:65)
at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure3.doCall(GradleUtil.groovy:102)
at org.grails.cli.gradle.GradleUtil$_withProjectConnection_closure3.call(GradleUtil.groovy)
at grails.io.support.SystemOutErrCapturer.withNullOutput(SystemOutErrCapturer.groovy:64)
at org.grails.cli.gradle.GradleUtil.withProjectConnection(GradleUtil.groovy:101)
at org.grails.cli.gradle.cache.CachedGradleOperation.call(CachedGradleOperation.groovy:65)
at org.grails.cli.GrailsCli.populateContextLoader(GrailsCli.groovy:514)
at org.grails.cli.GrailsCli.initializeProfile(GrailsCli.groovy:497)
at org.grails.cli.GrailsCli.initializeApplication(GrailsCli.groovy:308)
at org.grails.cli.GrailsCli.execute(GrailsCli.groovy:271)
at org.grails.cli.GrailsCli.main(GrailsCli.groovy:162)
| Error Error initializing classpath: Unsupported method: GrailsClasspath.getProfileDependencies().
The version of Gradle you connect to does not support that method.
To resolve the problem you can change/upgrade the target version of Gradle you connect to.
Alternatively, you can ignore this exception and read other information from the model.

**Comment by burtbeckwith** [comment]
This can't be related to the plugin, it's a jar file. Must be a configuration problem or something wrong with the version of Grails you're using.

**Comment by jontowles** [comment]
It seems to me that you guys don’t support Grails 3.1+

That method was introduced in Grails 3.1, which is what is throwing errors

Jon Towles
JJTowles@wellington.com<mailto:JJTowles@wellington.com>
Lead Systems Engineer (Mobility)
EDC-IT Efficiencies
508-486-4762

**Comment by burtbeckwith** [comment]
Right, not related to the plugin - report as a Grails issue
